### ISSUE TITLE
Installation problems 

### ISSUE THREAD

**Issue by rajavenks** [metrumresearchgroup/Torsten#2]
Hi 

I am trying to install the torsten and followed the procedure outlined in the torsten manual. I downloaded the torsten_master as a zip file. In R, I setwd-ed to the Torsten-master folder and tried to install torsten using source('install.R'). 

I am getting a following error. Anyone has an idea of how I can circumvent this. 

Thanks
rajavenks

[Torsten_Error_051818.txt](https://github.com/metrumresearchgroup/Torsten/files/2018583/Torsten_Error_051818.txt)

**Comment by rajavenks** [comment]
This is resolved for me. What worked is to correctly implement the inclusion of c++11 in CXXFLAGS as suggested in the installation help. 

> Please ensure CXXFLAGS in .R/Makevars constains flag -std=c++11.

Thanks
rv

**Comment by DuyTran16** [comment]
I had to reinstall Torsten on a different computer (windows 10).  The Makevars file were uncommented in skeleton folder in  RcppArmadillo and RcppEigen packages so that 
`CXX_STD = CXX11`
 
However installation problems similar to above except the following error message 

```
make: *** [C:/PROGRA~1/R/R-35~1.0/etc/x64/Makeconf:215: stanc.o] Error 1
ERROR: compilation failed for package 'rstan'
```

Can you help me figure out what could be the problem?
