### ISSUE TITLE
example-models: format and inconsistency with User Manual

### ISSUE THREAD

**Issue by billgillespie** [metrumresearchgroup/Torsten#4]
Currently the examples in Torsten/example-models vary in format and the examples intended to match with the User Manual are not fully consistent with the manual text.

I propose that the examples be more self-contained within their respective folders rather than spread between the example folder and the R folder (with the exception of shared function scripts like stanTools.R). The User Manual text and the corresponding examples should also be realigned to match.

**Comment by yizhang-cae** [comment]
The examples in the latest user guide at https://github.com/metrumresearchgroup/Torsten are actually generated by `include`, so they should be identical to the corresponding examples in the `example-models` in the same repo. If we have updated the upstream repo https://github.com/metrumresearchgroup/example-models, then we must update the same folder in the container repo.

**Comment by charlesm93** [comment]
@billgillespie I like the idea of having self-contained scripts. I'm however concerned about having duplicate code, since the R script can vary little (if not at all) between examples.

I think it would make sense to have a two compartment model folder, with one R script and three Stan implementations (to illustrate use of analytical, matrix exp, and numerical methods). Similarly the FK folder could have one R script with two models (full integration and mixed solving).

I'll add to this issue what I mentioned in issue #6, namely that the examples can be written more concisely using new language features.

**Comment by charlesm93** [comment]
A longer term goal: it would be nice to have a case study on fitting the population FK model. This includes a discussion on the mixed solver, diagnosing divergent transitions and centered / non-centered parameterizations, scaling the parameters for a full covariance analysis, and using within-chain parallelization. I think such a model could be fitted in ~ 2 hours if properly implemented. But yeah, there are a lot of computational techniques to deploy to get there.

**Comment by yizhang-cae** [comment]
It’s worth to have duplication in this case. If you look at CVODES examples they’re all duplications. Here being self-contained takes priority IMO.

Yi

**Comment by yizhang-yiz** [comment]
All examples are now reside in corresponding directory. Closing.
