### ISSUE TITLE
[BUG] failure to build example models

### ISSUE THREAD

**Issue by yizhang-yiz** [metrumresearchgroup/Torsten#48]
From https://discourse.mc-stan.org/t/problem-installing-torsten-0-90/27585/5?u=yizhang
by Casey Davis.

## Description
On new macbook pro with M3 chip:

```
48 warnings and 14 errors generated.
make: *** [src/cmdstan/main.o] Error 1
```
Is this something going on with a Torsten incompatibility with the M3 chip?

## Expected Output
Build success.

#### Current Version:
v0.90.0

[Full error msg](https://github.com/metrumresearchgroup/Torsten/files/13797393/torsten_installation_error.txt)

**Comment by cbdavis33** [comment]
Thanks for working on it, Yi. I don't have any compilation issues, now. But now I'm running into some bugs, but they're on the Torsten side rather than the Stan side, so I'm going to move the thread here.


Now on to the next couple of issues. In ```example-models.pk2cpt/pk2cpt.stan```, when compiling it as is, I get the error
```
Compiling Stan program...
Syntax error in '/var/folders/cq/ymsm1rv904b6mwygsq0z0z4w0000gn/T/RtmpYy3ugG/model-1132070f5fc31.stan', line 54, column 17 to column 18, parsing error:
   -------------------------------------------------
    52:  
    53:    cHat = x[2, :] ./ V1; // we're interested in the amount in the second compartment
    54:    cHatObs = cHat'[iObs]; // predictions for observed data recors
                          ^
    55:  
    56:  }
   -------------------------------------------------

Ill-formed phrase. Found L-value "=" expression. There are many ways in which this can be completed to a valid phrase.
```
This is no big deal, since changing to either ```cHatObs = cHat[iObs]'; // predictions for observed data recors``` or 
```
for(i in 1:nObs){
    cHatObs[i] = cHat[iObs[i]];  // predictions for observed data records
  }
```
as in pk2cpt_linode.stan
The ```pk2cpt_linode``` works perfectly, so I changed line 57 above to

**Comment by yizhang-yiz** [comment]
This has been fixed in the latest develop branch. Thanks for reporting still.
